# Generated by Django 3.1.3 on 2020-12-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_items', '0002_listitem_claimed_by'),
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(blank=True, to='list_items.ListItem'),
        ),
    ]
