# Generated by Django 3.1.3 on 2020-12-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0003_remove_wishlist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
