# Generated by Django 3.1.3 on 2020-12-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_items', '0002_listitem_claimed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='is_claimed',
        ),
    ]
