# Generated by Django 3.1.3 on 2020-12-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0003_remove_wishlist_items'),
        ('list_items', '0004_auto_20201202_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='parent',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='wishlists.wishlist'),
            preserve_default=False,
        ),
    ]
