# Generated by Django 3.1.3 on 2020-12-02 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0003_remove_wishlist_items'),
        ('list_items', '0005_listitem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listitems', to='wishlists.wishlist'),
        ),
    ]
